# This file is managed by `git_helper`. Don't edit it directly

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:

  - pip install pip lxml dummy_wx --upgrade
  - pip install -r requirements.txt
  - pip install tox tox-travis



script:
  - tox


stages:
  - test
  - deploy_pypi

  - deploy_releases

jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script:
        - python3 make_importable.py
      deploy:
        on:
          tags: true
          repo: domdfcoding/custom_wx_icons_humanity
        provider: pypi
        user: "DomDF"
        password:
          secure: None
        distributions: "sdist bdist_wheel"
        skip_existing: true


    - stage: deploy_releases
      python: "3.6"
      install:
        - pip install PyGithub requests
      script: skip
      deploy:
        on:
          repo: domdfcoding/custom_wx_icons_humanity
        provider: script
        script: python .ci/copy_pypi_2_github.py || return 1;
